[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "mkdir -p test/data",
  "touch test/data/05-versions-space.pdf"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"
